[project]
name = "pixi_gazebodistro"
version = "0.1.0"
description = "Add a short description here"
authors = ["Michael Carroll <mjcarroll@intrinsic.ai>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64", "linux-aarch64"]

[tasks]
sync = {cmd = "python helper.py sync"}
colcon = {cmd = "python helper.py colcon"}
build = {cmd = "python helper.py colcon build"}
test = {cmd = "python helper.py colcon test"}
clean = {cmd = "python helper.py clean"}

[dependencies]
eigen = "*"
pybind11 = "*"
tinyxml2 = "*"
libprotobuf = "*"
freeimage = "*"
assimp = "*"
ffmpeg = "*"
gts = "*"
glib = "*"
cppzmq = "*"
zeromq = "*"
libgdal = "*"
ogre = "1.10.*"
ogre-next = "*"
dartsim = "*"
bullet-cpp = "*"
psutil = "*"
ruby = "*"
libcurl = "*"
jsoncpp = "*"
libzip = "*"
yaml = "*"
qt-main = "*"

[target.linux-64.dependencies]
libglu = "*"
mesa-libgl-devel-cos7-x86_64 = "*"
mesa-libegl-devel-cos7-x86_64 = "*"
libglvnd-devel-cos7-x86_64 = "*"
vulkan-headers = "*"

[target.linux-aarch64.dependencies]
libglu = "*"
mesa-libgl-devel-cos7-aarch64 = "*"
mesa-libegl-devel-cos7-aarch64 = "*"
libglvnd-devel-cos7-aarch64 = "*"

[target.win-64.dependencies]
dlfcn-win32 = "*"

[build-dependencies]
ninja = "*"
make = "*"
cmake = "*"
git = "*"
vcstool = "*"
colcon-common-extensions = "*"
compilers = "*"
pkg-config = "*"
swig = "*"
