{
  "build": {
    "merge-install": true,
    "cmake-args": [
      "-GNinja",
      "--no-warn-unused-cli",
      "-DCMAKE_BUILD_TYPE=RelWithDebInfo",
      "-DCMAKE_BUILD_WITH_INSTALL_RPATH=ON",
      # BFD in conda is not compiled with fPIC
      "-DSTACK_DETAILS_AUTO_DETECT:BOOL=FALSE",
      "-DSTACK_DETAILS_BFD:BOOL=FALSE",
      # Docs not necessary
      "-DBUILD_DOCS:BOOL=FALSE"
    ],
    "event-handlers": [
      "console_cohesion+",
      "console_package_list+",
    ]
  },
  "test": {
    "merge-install": true,
    "event-handlers": [
      "console_direct+",
    ]
  }
}
